config globals 'globals'
    option iface 'br-lan'
    option enabled '1'
    option total_bandwidth '1000mbit'

config host 'pc1'
    option name 'PC-1'
    option ip '10.168.2.33'
    option download '20mbit'
    option download_mode 'ceil'
    option upload '5mbit'
    option upload_mode 'ceil'
    option enabled '1'

config host 'pc2'
    option name 'PC-2'
    option ip '10.168.1.25'
    option download '10mbit'
    option download_mode 'rate'
    option upload '3mbit'
    option upload_mode 'ceil'
    option enabled '1'
